// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8YY_GzO1d0NpYhjtiV2AdVz-7parWAL8',
    appId: '1:646397413235:web:7b1f149c16f359a5db6706',
    messagingSenderId: '646397413235',
    projectId: 'esp32-mors',
    authDomain: 'esp32-mors.firebaseapp.com',
    storageBucket: 'esp32-mors.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnhDIKNmMSpKEDQRIG9HlM5PclOsUaP4o',
    appId: '1:646397413235:android:32bf3091a659aa3ddb6706',
    messagingSenderId: '646397413235',
    projectId: 'esp32-mors',
    storageBucket: 'esp32-mors.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0cFDwQFTMVGlAxxNKzYCvnzPNqSQAoKI',
    appId: '1:646397413235:ios:f46a7a6699790881db6706',
    messagingSenderId: '646397413235',
    projectId: 'esp32-mors',
    storageBucket: 'esp32-mors.appspot.com',
    iosBundleId: 'com.example.esp32',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0cFDwQFTMVGlAxxNKzYCvnzPNqSQAoKI',
    appId: '1:646397413235:ios:f46a7a6699790881db6706',
    messagingSenderId: '646397413235',
    projectId: 'esp32-mors',
    storageBucket: 'esp32-mors.appspot.com',
    iosBundleId: 'com.example.esp32',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8YY_GzO1d0NpYhjtiV2AdVz-7parWAL8',
    appId: '1:646397413235:web:c3d181d02812a25fdb6706',
    messagingSenderId: '646397413235',
    projectId: 'esp32-mors',
    authDomain: 'esp32-mors.firebaseapp.com',
    storageBucket: 'esp32-mors.appspot.com',
  );

}